services:
  - type: web
    name: card-validation-api
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: CORS_ORIGIN
        sync: false
